name: Jobcode Scraper

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Firebase Key
        run: |
          mkdir -p serviceaccount
          echo '${{ secrets.FIREBASE_KEY }}' > serviceaccount/jobnride-97d77-firebase-adminsdk-fbsvc-20ce6e6129.json

      - name: Run scraper and update Firestore
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          SKIP_AI: ${{ secrets.OPEN_AI_API_KEY == '' && 'true' || 'false' }}
        run: python scrape_jobcode_to_firestore.py
